site_name: "tl;dr: Privacy"

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/shield-check
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    tag:
      default: material/tag-text
      credit: material/trophy-award
      req: material/exclamation
      misc: material/more
      help: material/information
      wip: material/pencil

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: CloneWith/tldr-privacy
      branch: main

markdown_extensions:
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  tags:
    credit: credit
    guide: help
    misc: misc
    WIP: wip
    collaboration: coop
    collab: coop
    request: req
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CloneWith

repo_url: https://github.com/CloneWith/tldr-privacy
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css
